    name: Build APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.4'
      
      - name: Build Debug APK
        working-directory: code   # ⚠️这里改成你实际放app的文件夹名
        run: gradle assembleDebug --no-daemon
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: delta-overlay-debug
          path: code/app/build/outputs/apk/debug/app-debug.apk  # ⚠️前缀也要改
